default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: test_only
  
test:
  <<: *default
  database: test_only

production:
  <<: *default
  database: receipe_app_production